= WDK API Tests
:gradleVersion: v4.10
:source-highlighter: pygments
:icons: font
:toc:

Test suite for use with the WDK API.

== How to run

=== Included shell script

Currently only available with bash or bash compatible shells.

.runner help text
[source, bash session]
----
$ ./run -h
Usage:

  run [args...] [-- gradle args...]

Arguments:

  -a <credentials>    Site login email address and password formatted as:

                          -a {email}:{password}

                      This can be specified more than once to provide multiple
                      users.  Leaving this out will disable tests that require a
                      user session.  Only specifying one set of credentials will
                      disable tests requiring more than one user.

                      This value can also be specified by setting the
                      CREDENTIALS environment variable to a JSON array of
                      objects containing the login email and password set as the
                      properties "email" and "pass" respectively.

  -c                  Clean run.  This runs gradle clean to clear out any
                      remnants of previous builds or test runs.

  -d                  Debug test run script (prints the commands that would be
                      run)

  -D <value>          Arbitrary JVM params.

  -f                  Force rerun tests.

  -h                  Show this help text

  -l                  Use legacy login scheme for authentication instead of
                      OAuth.

  -q                  QA Token.  "auth_tkt" value used to bypass the extra
                      login step for QA sites.  This value can be attained by
                      logging into a QA site in a browser and retrieving the
                      "auth_tkt" query param given after a successful login.

  -s <test>           Test class or method to run.  Allows wildcard matching
                      with '*'.  Can be specified multiple times to run multiple
                      tests.

  -t <tags>           Only run tests annotated with a tag in this comma
                      separated list of tags.

  -T <tags>           Exclude tests annotated with a tag in this comma separated
                      list of tags.

  -u <site url>       URL of the site which will have it's API tested.

                      This value can also be set using the SITE_PATH environment
                      variable.

  -v                  Print verbose test info (including HTTP request details).

Additional Params:

  [gradle args...]    Additional arguments/parameters that will be passed
                      to gradle.

Examples

  Run in interactive mode (or with env vars) and tell gradle to print
  stacktraces:

    run -- --stacktrace

  Run with single login and site:

    run -l -a some@email.addr:abc123 -u http://username.plasmodb.org/plasmo.username

  Run specific tests:

    run -s 'LoginTest' -s '*StepAnalysisTest$GetAnalysisDetails.invalidUserId'

  Exclude specific tags:

    run -T some,tags,to,exclude

  Run specific tags:

    run -t some,tags,to,run

----

==== Running Specific Tests

The shell script included accepts the arg `-s` which can be used to provide
one or more specific tests to run.  The argument value provided is a string that
allows wildcard matching to select which classes or methods to run.

To specify more than one test, use the `-s` flag multiple times.

.Running a specific test class
[source, bash session]
----
$ ./run -s 'LoginTest'
----

.Running a single test method
[source, bash session]
----
$ ./run -s 'QuestionsTest.getQuestions'
----

.Running a nested test class
[source, bash session]
----
$ ./run -s '*StepAnalysisTest$GetAnalysisDetails'
----

=== With gradle(w)

https://gradle.org[Gradle {gradleVersion}] is included and can be run using the
standard https://docs.gradle.org/current/userguide/gradle_wrapper.html[`gradlew`
or `gradlew.bat`] files.

When running with Gradle directly the options that would have been set using the
run script can be set as environment variables.  The full list of env vars and
options are defined below in the <<environment>> section.

.gradle run
[source, bash session]
----
$ SITE_PATH="..." ./gradlew test
----

== Specialized Tags

=== Site specific tests

The test runner will automatically determine which site you are testing against
and disable tests that are specifically marked with <<tagging,tags>> as tests
for other sites.  For example if tests are run for the site
`http://plasmodb.org/plasmo`, tests annotated with `clinepi`, `fungi`, `toxo`,
etc. will be excluded from the test run.

Tests that are not tagged with one of the specific tags below will not be
affected by the site specific testing and will be included in the test run
(unless otherwise enabled/disabled using the `-t/-T` flags).

The sites/tags known to the test runner are:

* `amoebadb`
* `clinepidb`
* `cryptodb`
* `eupathdb`
* `fungidb`
* `giardiadb`
* `hostdb`
* `microbiomedb`
* `microsporidiadb`
* `orthomcl`
* `piroplasmadb`
* `plasmodb`
* `toxodb`
* `trichdb`
* `tritrypdb`
* `vectorbase`

To mark a test as being data-specific to one particular site, mark the test with
the `@Tag` annotation including the name of the site from the list above.  Please
use the constants in Category.java as below.

.Example
[source, java]
----
@Tag(Category.ORTHOMCL_TEST)
void someTestMethod() {
  ...
}
----

=== Auth / Multi-Auth tests

If a test requires an authenticated session it should be annotated with
`@Tag("auth")` or `@Tag("multi-auth")` these specific tags will allow the test
runner to enable or disable these tests based on whether or not the run command
included user credentials.

The explanation of each of those tags and their differences:

`@Tag("auth")`::
  The `auth` tag is used for marking tags that only require a single
  authenticated user to run.  This should cover most cases.
`@Tag("multi-auth")`::
  The `multi-auth` tag is used to mark tests which require more than one user
  session at a time

WARNING: If a test requires a user session and is not annotated with an auth
         tag, it _will_ fail on run.

== Configuration


[[environment]]
=== Environment

==== `SITE_PATH`

*REQUIRED*

The URL for the site which will have it's API tested, including the protocol.

.Example
[source, bash]
----
SITE_PATH="http://plasmodb.org/plasmo"
----

==== `CREDENTIALS`

JSON array containing user login credentials.

.Example
[source, bash]
----
CREDENTIALS='{"email":"somebody@site.com","pass":"password1"}'
----

==== `AUTH_TYPE`

OPTIONAL

Authentication scheme to use when authenticating with the specified site.

Possible values:

* `OAUTH` (default value)
* `LEGACY`


[[tagging]]
=== Test Tagging

JUnit5 allows the use of an `@Tag` annotation to mark tests, this can then be
used to whitelist or blacklist tests to run.

Using the `-t` or `-T` flags it is possible to control which tags are run or
excluded using the test runner.

Both the `-t` and `-T` flags expect a comma separated list of tag strings such
as `-t foo,bar -T fizz,buzz`.

See the https://junit.org/junit5/docs/current/user-guide/#writing-tests-tagging-and-filtering[JUnit documentation for test tagging]
