= Karate API Tests
Ellie Harper <epharper@upenn.edu>
v1.0, 2018-08-27
:toc:

Documentation of setup and usage of Karate API tests for WDK service endpoints.

For documentation and downloads for the Karate project itself see
https://github.com/intuit/karate.

== Setup

=== Install

An automatic install shell script is in the root directory of the project.  It
will download and package Karate as a "self-executable" jar, then request sudo
access to install Karate in `/usr/local/bin`.

[source, bash]
----
$ ./karate-setup.sh
Installing Karate
Downloading version "v0.8.0"
######################################################################### 100.0%
Packaging
[sudo] password for <username>: 
Performing cleanup
----

=== Configure

Karate reads it's configuration from the included `karate-config.js` file.  This
javascript file contains a single nameless function which returns an object
containing run time variables for karate.

Additional configuration can be done in this function, for more info reference
https://github.com/intuit/karate#configuration[the Karate readme]

The options presently used by our tests are:

`baseUrl`::
  The base path to the site that should be tested.  Examples:
  * `\http://plasmodb.vm.ebrc.org/plasmo.vm`
  * `\http://toxodb.org/toxo`
`username`::
  Username to use for login
`password`::
  Password to use for login

== Running

.default config
[source, bash]
----
$ karate
10:53:41.511 [main] INFO  com.intuit.karate.netty.Main - Karate version: 0.8.0.1
10:53:41.729 [main] INFO  c.i.karate.cucumber.CucumberRunner - Karate version: 0.8.0.1
...
====================================================
elapsed time: 7.15 | total thread time: 6.85
features:     2 | threads:   1 | efficiency: 0.96
scenarios:    2 | failed:    0 | skipped:    0
====================================================
----

=== Customized Run

==== Test Selection

By default Karate will run all tests found in the `./tests` directory which are
not prefixed with the `@ignore` annotation.

To override this and run specific tests, pass the paths to those feature files
as parameters to Karate:

[source, bash]
----
$ karate tests/service/login.feature tests/etc...
----

==== Options

The following options can be provided as environment variables:

`JVM_ARGS`::
  Pass additional arguments to the JVM.
+
.example: pass `foo=bar` setting to the jvm
[source, bash]
----
$ JVM_ARGS="-Dfoo=bar" karate
----

`TAGS`::
  Pass a comma separated list of Cucumber tags to modify test behavior
+
.example: only run test which are normally ignored
----
$ TAGS="@ignore" karate
----