= WDK API Tests
:gradleVersion: v4.10
:source-highlighter: pygments
:icons: font
:toc:

Test suite for use with the WDK API.

== How to run

=== Included shell script

Currently only available with bash or bash compatible shells.

.runner help text
[source, bash session]
----
$ ./run -h
Usage:

  run [args...] [-- gradle args...]

Arguments:

  -e <email address>    Default site login email address.  If this value is not
                        provided it will be requested interactively.

                        This value can also be set using the EMAIL environment
                        variable.

  -p <password>         Default site login password.  If this value is not
                        provided it will be requested interactively.

                        This value can also be set using the PASSWORD
                        environment variable.

  -u <site url>         URL of the site which will have it's API tested.  If
                        this value is not provided it will be requested
                        interactively.

                        This value can also be set using the SITE_PATH
                        environment variable.

  -s <test>             Test class or method to run.  Allows wildcard matching
                        with '*'.  Can be specified multiple times to run
                        multiple tests.

  -c                    Clean run.  This runs gradle clean to clear out any
                        remnants of previous builds or test runs.

  -l                    Use legacy login scheme for authentication instead of
                        OAuth.

  -D <value>            Arbitrary JVM params.

  -t <tags>             Only run tests annotated with a tag in this comma
                        separated list of tags.

  -T <tags>             Exclude tests annotated with a tag in this comma
                        separated list of tags.

  -h                    Show this help text

Additional Params:

  [gradle args...]        Additional arguments/parameters that will be passed
                          to gradle.

Examples

  Run in interactive mode (or with env vars) and tell gradle to print
  stacktraces:

    run -- --stacktrace

  Run with all run args:

    run -l -e some@email.addr -p abc123 -u http://site.com/thing

  Run specific tests:

    run -s 'LoginTest' -s '*StepAnalysisTest\$GetAnalysisDetails.invalidUserId'

  Exclude specific tags:

    run -T some,tags,to,exclude

  Run specific tags:

    run -t some,tags,to,run
----

==== Running Specific Tests

The shell script included accepts the arg `-s` which can be used to provide
one or more specific tests to run.  The argument value provided is a string that
allows wildcard matching to select which classes or methods to run.

To specify more than one test, use the `-s` flag multiple times.

.Running a specific test class
[source, bash session]
----
$ ./run -s 'LoginTest'
----

.Running a single test method
[source, bash session]
----
$ ./run -s 'QuestionsTest.getQuestions'
----

.Running a nested test class
[source, bash session]
----
$ ./run -s '*StepAnalysisTest$GetAnalysisDetails'
----

=== With gradle(w)

https://gradle.org[Gradle {gradleVersion}] is included and can be run using the
standard https://docs.gradle.org/current/userguide/gradle_wrapper.html[`gradlew`
or `gradlew.bat`] files.

When running with Gradle directly the options that would have been set using the
run script can be set as environment variables.  The full list of env vars and
options are defined below in the <<environment>> section.

.gradle run
[source, bash session]
----
$ EMAIL="..." PASSWORD="..." SITE_PATH="..." ./gradlew test
----


== Configuration


[[environment]]
=== Environment

==== `SITE_PATH`

*REQUIRED*

The URL for the site which will have it's API tested, including the protocol.

.Example
[source, bash]
----
SITE_PATH="http://plasmodb.org/plasmo"
----

==== `EMAIL`

*REQUIRED*

Login email address to use for authenticating with the specified site.

.Example
[source, bash]
----
EMAIL="somebody@site.com"
----

==== `PASSWORD`

*REQUIRED*

Login password to use for authenticating with the specified site.

.Example
[source, bash]
----
PASSWORD="abc123"
----

WARNING: Consider using an environment file or `.envrc` to avoid putting this in
your shell history.

==== `AUTH_TYPE`

OPTIONAL

Authentication scheme to use when authenticating with the specified site.

Possible values:

* `OAUTH` (default value)
* `LEGACY`
